apm-server:
  host: 0.0.0.0:8200

output.elasticsearch:
  hosts: ["http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}

apm-server.ssl:
  enabled: true
  certificate: /certs/apm-server.crt
  certificate_authorities: /certs/ca.crt
  key: /certs/apm-server.key
  # Fixme Remove when using signed certificates
  client_authentication: 'optional'
